# syntax = docker/dockerfile:1.23

FROM node:22.22-alpine AS base
RUN corepack enable
WORKDIR /base
COPY --link package.json yarn.lock .yarnrc.yml ./
RUN --mount=type=cache,target=/tmp/yarn_cache \
  YARN_CACHE_FOLDER=/tmp/yarn_cache \
  yarn install --immutable

FROM node:22.22-alpine
RUN corepack enable
WORKDIR /base
COPY --link --from=base /base ./
COPY --link . .
# upload Source Maps to sentry
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_RELEASE
ARG SENTRY_DIST
RUN SENTRY_AUTH_TOKEN="${SENTRY_AUTH_TOKEN}" \
      SENTRY_RELEASE="${SENTRY_RELEASE}" \
      yarn build
