FROM node:15.14.0-alpine3.11 AS base
WORKDIR /base
COPY package*.json ./
RUN npm install
COPY . .

FROM base AS build
ENV NODE_ENV=production
WORKDIR /build
COPY --from=base /base ./
RUN npm run export

FROM nginx:alpine
RUN mkdir -p /usr/share/nginx/html/cndt2021/ui
COPY --from=build /build/out /usr/share/nginx/html/cndt2021/ui
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 3001
