import { Talk } from '../interfaces'

export const Talks: Talk[] = [
  {
    id: 1,
    trackId: '1',
    vimeoId: '453943528',
    title: 'ほげふが',
    description: 'ぴよぴよ',
    speakers: ['jacopen1', 'r_takaishi2'],
  },
  {
    id: 2,
    trackId: '1',
    vimeoId: '450845161',
    title: 'ふー',
    description: 'ばー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
  {
    id: 3,
    trackId: '1',
    vimeoId: '453963160',
    title: 'ほげほげほげ',
    description: 'ぴよぴよぴよ',
    speakers: ['jacopen1', 'r_takaishi2'],
  },
  {
    id: 4,
    trackId: '1',
    vimeoId: '453941938',
    title: 'ほげーーーーーー',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
  },
  {
    id: 5,
    trackId: '2',
    vimeoId: '453942665',
    title: 'こんぺこ',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
  },
  {
    id: 6,
    trackId: '2',
    vimeoId: '453943218',
    title: 'にゃっはろー',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
  {
    id: 7,
    trackId: '2',
    vimeoId: '453939601',
    title: 'てすとてすと',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
  },
  {
    id: 8,
    trackId: '3',
    vimeoId: '453936668',
    title: 'あいうえおかきくけこ',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
  {
    id: 9,
    trackId: '4',
    vimeoId: '453936358',
    title: 'ぷぎゃー',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
  {
    id: 10,
    trackId: '5',
    vimeoId: '453935827',
    title: 'ぽぎゃー',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
  {
    id: 11,
    trackId: '6',
    vimeoId: '450845161',
    title: 'ばー',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
]
