import { Talk } from '../interfaces'

export const Talks: Talk[] = [
  {
    id: 1,
    trackId: '1',
    vimeoId: '453942665',
    title: 'ほげふが(talkId = 1)',
    description: 'ぴよぴよ',
    speakers: ['jacopen1', 'r_takaishi2'],
  },
  {
    id: 2,
    trackId: '1',
    vimeoId: '450845161',
    title: 'ふー(talkId = 2)',
    description: 'ばー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
  {
    id: 3,
    trackId: '1',
    vimeoId: '453963160',
    title: 'ほげほげほげ(talkId = 3)',
    description: 'ぴよぴよぴよ',
    speakers: ['jacopen1', 'r_takaishi2'],
  },
  {
    id: 4,
    trackId: '1',
    vimeoId: '453941938',
    title: 'ほげーーーーーー(talkId = 4)',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
  },
  {
    id: 5,
    trackId: '2',
    vimeoId: '453943528',
    title: 'こんぺこ(talkId = 5)',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
  },
  {
    id: 6,
    trackId: '2',
    vimeoId: '453943218',
    title: 'にゃっはろー(talkId = 6)',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
  {
    id: 7,
    trackId: '2',
    vimeoId: '453939601',
    title: 'てすとてすと(talkId = 7)',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
  },
  {
    id: 8,
    trackId: '3',
    vimeoId: '453936668',
    title: 'あいうえおかきくけこ(talkId = 8)',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
  {
    id: 9,
    trackId: '4',
    vimeoId: '453936358',
    title: 'ぷぎゃー(talkId = 9)',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
  {
    id: 10,
    trackId: '5',
    vimeoId: '453935827',
    title: 'ぽぎゃー(talkId = 10)',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
  {
    id: 11,
    trackId: '6',
    vimeoId: '450845161',
    title: 'ばー(talkId = 11)',
    description: 'ぴよーーーーーーー',
    speakers: ['jacopen1', 'r_takaishi2'],
    onAir: true,
  },
]
