name: build container image when tags are pushed

on:
  push:
    tags: ["*"]

jobs:
  build:
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/wc-build-image.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      image_name: dreamkast-ui
      platforms: amd64
      aws_region: ap-northeast-1
      run-trivy: false
      build-args: SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
