name: build container image when branches are pushed

on:
  push:
    branches: ["*"]

jobs:
  build:
    if: github.event.pusher.name != 'dreamkast-cloudnativedays'
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/wc-build-image.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      image_name: dreamkast-ui
      aws_region: us-west-2
      run-trivy: true
      build_args: |
        SENTRY_RELEASE=${{ github.sha }}

  upload-sourcemaps:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Build
        id: docker_build
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        with:
          context: ./
          file: Dockerfile-upload-source-maps
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          cache-from: type=gha
          build-args: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_RELEASE=${{ github.sha }}
