name: build container image when tags are pushed

on:
  push:
    tags: ["*"]

jobs:
  build:
    uses: cloudnativedaysjp/reusable-workflows/.github/workflows/wc-build-image.yml@main
    permissions:
      contents: read
      id-token: write
    with:
      image_name: dreamkast-ui
      platforms: amd64
      aws_region: ap-northeast-1
      run-trivy: false
      build_args: |
        SENTRY_RELEASE=${{ github.ref_name }}

  upload-sourcemaps:
    needs: build  # to use build cache
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build
        id: docker_build
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          context: ./
          file: Dockerfile-upload-source-maps
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          cache-from: type=gha
          build-args: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            SENTRY_RELEASE=${{ github.ref_name }}
