name: debug

on:
  pull_request:
    branches-ignore:
      - 'renovate/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          HEAD_REF: ${{ github.head_ref }}
        run: |
          echo "name: ${{ github.event_name }} path: ${{ github.event_path }} ref: ${{ github.ref }} head_ref: $HEAD_REF"

