name: GitOps for production

on:
  push:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/gitops-prd.yml'
      - '**.md'
    tags:
      - v*

jobs:
  gitops:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout dreamkast-infra
        uses: actions/checkout@v3
        with:
          repository: cloudnativedaysjp/dreamkast-infra
          path: dreamkast-infra
          token: ${{ steps.generate_token.outputs.token }}

      - name: Update Kubernetes resources
        working-directory: dreamkast-infra/manifests/app/dreamkast/overlays/production/main
        run: |
          kustomize edit set image dreamkast-ui=${{ steps.login-ecr.outputs.registry }}/dreamkast-ui:${{ github.sha }}

      - name: Commit files
        working-directory: dreamkast-infra/
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add -A
          git commit -am "Bump docker tag (${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA})"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          repository: cloudnativedaysjp/dreamkast-infra
          directory: dreamkast-infra
          branch: production/ui-main

      - name: Create and Merge Pull Request
        uses: "actions/github-script@v2"
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          script: |
            const pr = await github.pulls.create({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              title: "Automated PR (production/ui-main)",
              body: "**this PR is automatically created & merged**",
              head: "production/ui-main",
              base: "main"
            });
            await github.pulls.merge({
              owner: "cloudnativedaysjp",
              repo: "dreamkast-infra",
              pull_number: pr.data.number,
              merge_method: "merge",
            });
