name: jest
on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/jest.yml'
      - '**.md'
    types: [opened, synchronize]
jobs:
  jest:
    name: jest
    runs-on: ubuntu-latest
    if: github.event.pusher.name != 'dreamkast-cloudnativedays'
    permissions:
      contents: read
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          persist-credentials: false
      - name: Set up Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: yarn install
        run: yarn install
      - name: jest
        run: yarn test
