name: jest
on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/jest.yml'
      - '**.md'
    types: [opened, synchronize]
jobs:
  jest:
    name: jest
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.pull_request.title, '[dreamkast-releasebot]') }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node.js 16.17.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.17.0
          cache: 'yarn'
      - name: yarn install
        run: yarn install
      - name: jest
        run: yarn test
