name: jest
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  jest:
    name: jest
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.pull_request.title, '[dreamkast-releasebot]') }}
    steps:
      - uses: actions/checkout@v1
      - name: yarn install
        run: yarn install
      - name: jest
        run: yarn test
