name: jest
on:
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/jest.yml'
      - '**.md'
    types: [opened, synchronize]
jobs:
  jest:
    name: jest
    runs-on: ubuntu-latest
    if: github.event.pusher.name != 'dreamkast-cloudnativedays'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'
      - name: yarn install
        run: yarn install
      - name: jest
        run: yarn test
